### PR TITLE
Incorrect track bug smallest absolute value match

### PR DESCRIPTION
**Pull request by rocky**

### CODE REVIEW

**Comment by rocky** [comment]
@enzo1982 would you do the final review here?

**Comment by enzo1982** [comment]
Yes, I'll have a look at it!

**Comment by enzo1982** [comment]
All looks good now; I merged the pull request.

One more thing, though: I would suggest that we keep the cdda2.bin test file in git. We can exclude it from release tarballs by not adding it to Makefile.am. That way tarballs stay small and we still has easy access to the test file - everybody wins.

**Comment by rocky** [comment]
>One more thing, though: I would suggest that we keep the cdda2.bin test file in git. 

Makes sense. Feel free to add it from https://mega.nz/#!alBBhS7Q!C3O48z4GcNtcqEpVZe01S6MjyGt-0kGfHyjpdecosFU I think we've tested that it already is excluded from the tarball.

**Comment by enzo1982** [comment]
> Feel free to add it

Done

**Pull request merged**
